### ISSUE TITLE
导致VS2022崩溃

### ISSUE THREAD

**Issue by YiboH** [Entity-Now/EnTranslate#2]
![微信图片_20230716155730](https://github.com/Entity-Now/EnTranslate/assets/36151083/cc516bbb-ee9e-491d-a550-0a7ea0c84bca)
![微信图片_20230716155743](https://github.com/Entity-Now/EnTranslate/assets/36151083/2a4e7e2d-79ad-4825-8b56-b2ab27a67af4)

**Comment by YiboH** [comment]
VS2022更新到最新的17.7.2版本后，24小时之内出现多次崩溃，是否和VS版本有关？
![微信图片_20230823143554](https://github.com/Entity-Now/EnTranslate/assets/36151083/3dc6d40b-5ff1-4a74-941f-eed2fcfaf3d3)
![微信图片_20230823143354](https://github.com/Entity-Now/EnTranslate/assets/36151083/bd323ae5-6952-4d29-9f22-90e07c6e7a4f)

**Comment by Entity-Now** [comment]
插件已经更新到v2版本，使用的新的api。如果你用着还有问题，可以再提交issue

**Comment by YiboH** [comment]
偶尔当鼠标扫过到XML标签，或者WPF页面的标签时，导致VS卡住停止工作

**Comment by YiboH** [comment]
![微信图片_20231010175322](https://github.com/Entity-Now/EnTranslate/assets/36151083/31ef9778-1767-4314-8ab5-c6a86d9a26ec)
例如鼠标定位到6.0，VS卡死
