### ISSUE TITLE
探讨

### ISSUE THREAD

**Issue by DullSword** [Entity-Now/EnTranslate#3]
- 点击“试听”能否改为点击播放按钮
- 有些单独的单词没有识别出来，直接整个部分都是空白，能否有提示（我测试时还以为没生效）
![image](https://github.com/Entity-Now/EnTranslate/assets/40877476/d8bec639-07ca-4fab-8c30-5a7aaab51690)
- 配置里的“白色主题”，我没有勾选时，表现上就已经是白色主题了，勾选后也还是表现正常，这是什么情况
- 保存配置会保存到当前项目下，能否是保存到VS下

我不知道这些是否好搞，作者根据自己的情况来吧，希望能越做越好。

**Comment by Entity-Now** [comment]
okk，这些问题晚点都会修复。你这个单词估计是离线词库里面没有，我在考虑添加在线翻译的功能

**Comment by Entity-Now** [comment]
hello，你提的问题都已经修复了。如果有遇到新的问题，可以再提交issue。祝你生活愉快~
