### ISSUE TITLE
大佬，只差一个联网翻译了。

### ISSUE THREAD

**Issue by jianweie** [Entity-Now/EnTranslate#4]
大佬，只差一个联网翻译了。就完美了。现在划词搜索还是要跳转第三方不是体验很好，如果能划词直接弹出面板或者按个什么键就实现了，那就完美。期待后面的版本。

**Comment by Entity-Now** [comment]
这个不难，等有空我弄一下

**Comment by jianweie** [comment]
大佬加油。
