### ISSUE TITLE
鼠标悬停选中等均没有显示 does not display translation information.

### ISSUE THREAD

**Issue by aoaoms** [Entity-Now/EnTranslate#6]
感谢你的创作！

我离线安装了插件，重启VS2022 版本17.7.6；鼠标悬停选中等均没有显示翻译信息。若需要其他操作请辅助指出，谢谢。
mouse hover selection, does not display translation information.

![a](https://github.com/Entity-Now/EnTranslate/assets/44873565/1f081f19-3a55-4d85-b11e-cbf8f6600e85)
![b](https://github.com/Entity-Now/EnTranslate/assets/44873565/df443d16-1c1e-4b4b-9683-e8e4864fa502)

**Comment by Entity-Now** [comment]
因为不支持razor这种文件格式，不知道什么原因光标悬浮在xml的元素名上会导致vs崩溃

**Comment by aoaoms** [comment]
> 因为不支持razor这种文件格式，不知道什么原因光标悬浮在xml的元素名上会导致vs崩溃

好的，感谢。建议可以在文档注明。
